In [1]:
import pandas as pd
import numpy as np
from datetime import date, time, datetime, timedelta
from dateutil.relativedelta import relativedelta
import dash
import dash_html_components as html
import dash_core_components as dcc
from dash_html_components import Div, H1, H2, P, H3
from dash_core_components import Graph, Slider, Checklist, Dropdown
from dash.dependencies import Input , Output
import dash_bootstrap_components as dbc
import plotly.express as px
import plotly.graph_objects as go

C:\Users\marce\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\marce\anaconda3\lib\site-packages\numpy\.libs\libopenblas.4SP5SUA7CBGXUEOC35YP2ASOICYYEQZZ.gfortran-win_amd64.dll
C:\Users\marce\anaconda3\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
C:\Users\marce\AppData\Local\Temp\ipykernel_964\1729247805.py:9: UserWarning:
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html
C:\Users\marce\AppData\Local\Temp\ipykernel_964\1729247805.py:10: UserWarning:
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc

In [2]:
#Bases
df_cambio = pd.read_excel('Câmbio.xlsx')
df_Pib = pd.read_excel ('PIB_%.xlsx')
df_export = pd.read_excel ('Exportação.xlsx')
df_ipca = pd.read_excel ('IPCA.xlsx')
df_selic = pd.read_excel ('Selic.xlsx')
df_gpd_world = pd.read_excel ('GPD_Trismetral.xlsx', sheet_name = 'GPD')

In [3]:
df_gpd = pd.merge(df_Pib, df_gpd_world, on = ['Ano', 'Trimestre'])
df_gpd = df_gpd  [['Ano', 'Trimestre', 'PIB', 'gpd_world']]
df_gpd ['Ano Trimestre'] = df_gpd ['Ano'].astype(str) +" - " + df_gpd ['Trimestre']
df_gpd = df_gpd.query ('Ano>=2016')
df_gpd['GPD_World'] = df_gpd['gpd_world'].round(decimals=2)
df_gpd['PIB'] = df_gpd['PIB'].round(decimals=4)

df_gpd

     Ano     Trimestre  PIB  gpd_world        Ano Trimestre  GPD_World
72  2016  1º Trimestre -4.4   0.532812  2016 - 1º Trimestre       0.53
73  2016  2º Trimestre -4.5   0.598436  2016 - 2º Trimestre       0.60
74  2016  3º Trimestre -4.1   0.609616  2016 - 3º Trimestre       0.61
75  2016  4º Trimestre -3.3   1.080428  2016 - 4º Trimestre       1.08
76  2017  1º Trimestre -1.9   0.605326  2017 - 1º Trimestre       0.61
77  2017  2º Trimestre -0.9   0.991332  2017 - 2º Trimestre       0.99
78  2017  3º Trimestre  0.1   0.875774  2017 - 3º Trimestre       0.88
79  2017  4º Trimestre  1.3   0.902279  2017 - 4º Trimestre       0.90
80  2018  1º Trimestre  1.7   0.710334  2018 - 1º Trimestre       0.71
81  2018  2º Trimestre  1.9   0.643531  2018 - 2º Trimestre       0.64
82  2018  3º Trimestre  2.0   0.482009  2018 - 3º Trimestre       0.48
83  2018  4º Trimestre  1.8   0.518952  2018 - 4º Trimestre       0.52
84  2019  1º Trimestre  1.5   0.673000  2019 - 1º Trimestre       0.67
85  2019  2º Trimestre  1.4   0.668618  2019 - 2º Trimestre       0.67
86  2019  3º Trimestre  1.2   0.421366  2019 - 3º Trimestre       0.42
87  2019  4º Trimestre  1.2   0.291635  2019 - 4º Trimestre       0.29
88  2020  1º Trimestre  1.1  -1.783954  2020 - 1º Trimestre      -1.78
89  2020  2º Trimestre -1.7  -9.687602  2020 - 2º Trimestre      -9.69
90  2020  3º Trimestre -2.8   8.691235  2020 - 3º Trimestre       8.69
91  2020  4º Trimestre -3.3   1.578761  2020 - 4º Trimestre       1.58
92  2021  1º Trimestre -3.0   1.071963  2021 - 1º Trimestre       1.07
93  2021  2º Trimestre  2.4   1.528193  2021 - 2º Trimestre       1.53
94  2021  3º Trimestre  4.3   1.697762  2021 - 3º Trimestre       1.70
95  2021  4º Trimestre  5.0   1.486182  2021 - 4º Trimestre       1.49
96  2022  1º Trimestre  5.2   0.754001  2022 - 1º Trimestre       0.75
97  2022  2º Trimestre  3.2   0.669770  2022 - 2º Trimestre       0.67
98  2022  3º Trimestre  3.0   0.436436  2022 - 3º Trimestre       0.44

In [4]:
# merge dos dataframes

df_selic_ipca = pd.merge (df_selic,df_ipca, on = ['Período', 'Ano', 'Mês'])
df_selic_ipca = df_selic_ipca[['Período','Ano', 'Mês', 'Selic', 'IPCA']]
df_selic_ipca = df_selic_ipca.query ('Ano>=2019' )

df_cambio_export = pd.merge(df_cambio,df_export, on =['Ano', 'Trimestre'])
df_cambio_export = df_cambio_export[['Ano', 'Trimestre', 'cotacaoVenda', 'Export']]
df_cambio_export.rename(columns = {'cotacaoVenda':'Câmbio'}, inplace = True)

df_cambio_export = df_cambio_export.query ('Ano>=2016')
df_cambio_export['Câmbio'] = df_cambio_export['Câmbio'].round(decimals=2)
df_cambio_export ['Ano_trimestre'] = df_cambio_export['Ano'].astype (str) + ' - ' + df_cambio_export['Trimestre']

df_cambio_export

      Ano     Trimestre  Câmbio  Export        Ano_trimestre
80   2016  1º Trimestre    3.90  195364  2016 - 1º Trimestre
81   2016  2º Trimestre    3.51  208110  2016 - 2º Trimestre
82   2016  3º Trimestre    3.25  192894  2016 - 3º Trimestre
83   2016  4º Trimestre    3.30  185209  2016 - 4º Trimestre
84   2017  1º Trimestre    3.15  192342  2017 - 1º Trimestre
85   2017  2º Trimestre    3.22  216286  2017 - 2º Trimestre
86   2017  3º Trimestre    3.16  210484  2017 - 3º Trimestre
87   2017  4º Trimestre    3.25  205322  2017 - 4º Trimestre
88   2018  1º Trimestre    3.24  212294  2018 - 1º Trimestre
89   2018  2º Trimestre    3.61  248775  2018 - 2º Trimestre
90   2018  3º Trimestre    3.95  288213  2018 - 3º Trimestre
91   2018  4º Trimestre    3.81  275773  2018 - 4º Trimestre
92   2019  1º Trimestre    3.77  230541  2019 - 1º Trimestre
93   2019  2º Trimestre    3.92  263374  2019 - 2º Trimestre
94   2019  3º Trimestre    3.97  278699  2019 - 3º Trimestre
95   2019  4º Trimestre    4.12  270947  2019 - 4º Trimestre
96   2020  1º Trimestre    4.47  259988  2020 - 1º Trimestre
97   2020  2º Trimestre    5.39  322445  2020 - 2º Trimestre
98   2020  3º Trimestre    5.38  334877  2020 - 3º Trimestre
99   2020  4º Trimestre    5.39  334738  2020 - 4º Trimestre
100  2021  1º Trimestre    5.48  359295  2021 - 1º Trimestre
101  2021  2º Trimestre    5.29  482717  2021 - 2º Trimestre
102  2021  3º Trimestre    5.23  459533  2021 - 3º Trimestre
103  2021  4º Trimestre    5.59  439196  2021 - 4º Trimestre
104  2022  1º Trimestre    5.23  439627  2022 - 1º Trimestre
105  2022  2º Trimestre    4.93  514166  2022 - 2º Trimestre
106  2022  3º Trimestre    5.25  541272  2022 - 3º Trimestre

In [5]:
df_cambio_export ['Ano_trimestre'] = df_cambio_export['Ano'].astype (str) + ' - ' + df_cambio_export['Trimestre']

In [6]:
#tabelas plot
tb_selic_ipca = df_selic_ipca.query('Ano>=2022')

tb_cambio_export = df_cambio_export.query ('Ano>=2021')
tb_cambio_export['Export'] = tb_cambio_export['Export'].apply(lambda x : '{:,.2f}'.format(x))

tb_Pib = df_gpd.query ('Ano>=2021')

tb_Pib

C:\Users\marce\AppData\Local\Temp\ipykernel_964\2237109319.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tb_cambio_export['Export'] = tb_cambio_export['Export'].apply(lambda x : '{:,.2f}'.format(x))

     Ano     Trimestre  PIB  gpd_world        Ano Trimestre  GPD_World
92  2021  1º Trimestre -3.0   1.071963  2021 - 1º Trimestre       1.07
93  2021  2º Trimestre  2.4   1.528193  2021 - 2º Trimestre       1.53
94  2021  3º Trimestre  4.3   1.697762  2021 - 3º Trimestre       1.70
95  2021  4º Trimestre  5.0   1.486182  2021 - 4º Trimestre       1.49
96  2022  1º Trimestre  5.2   0.754001  2022 - 1º Trimestre       0.75
97  2022  2º Trimestre  3.2   0.669770  2022 - 2º Trimestre       0.67
98  2022  3º Trimestre  3.0   0.436436  2022 - 3º Trimestre       0.44

In [ ]:
app = dash.Dash(__name__,  external_stylesheets = [dbc.themes.CYBORG])

fig_selic = go.Figure(layout = {"template": "plotly_dark"})
fig_selic.add_trace (go.Scatter (x = df_selic_ipca ['Período'] , y = df_selic_ipca ['Selic'], name = 'Selic'))

fig_selic.add_trace (go.Scatter (x = df_selic_ipca['Período'], y = df_selic_ipca['IPCA'], name = 'IPCA'))

fig_selic.update_xaxes (tickangle = 45, tickfont_size = 6, dtick = "M1", tickformat = "%b\n%Y",showgrid=False)
fig_selic.update_yaxes (tickfont_size = 10, showgrid=False)

fig_selic.update_layout (
    #title = 'Selic',
    autosize = True,
    margin = dict(l=40,r=40,t=40,b=40),
    legend = dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x= 1.02)    
    )

fig_cambio_export = go.Figure (layout ={"template": "plotly_dark"})
fig_cambio_export.add_trace (go.Scatter (x = df_cambio_export['Ano_trimestre'], y = df_cambio_export['Câmbio'], 
                                         name = "Câmbio"))

fig_cambio_export.add_trace (go.Scatter (x = df_cambio_export['Ano_trimestre'], y = df_cambio_export['Export'], 
                                         name = "Export", yaxis="y2"))

fig_cambio_export.update_xaxes (tickangle = 45, tickfont_size = 6, showgrid=False)
fig_cambio_export.update_yaxes (tickfont_size = 10, showgrid=False)

fig_cambio_export.update_layout(
    yaxis = dict (title=dict(text="Câmbio"),side="left", showgrid=False),
    yaxis2 = dict (title=dict(text="Export"),side="right",overlaying="y", tickmode='array', showgrid=False),
    
    autosize= True,
    margin=dict(l=30,r=30,t=30,b=30),
    legend = dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x= 1.02)
    )

fig_pib = go.Figure(layout = {"template": "plotly_dark"})
fig_pib.add_trace (go.Scatter (x = df_gpd['Ano Trimestre'], y = df_gpd['PIB'], name = 'Pib Brasil'))
fig_pib.add_trace (go.Scatter (x = df_gpd['Ano Trimestre'], y = df_gpd['gpd_world'], name = 'Pib mundo'))
fig_pib.update_xaxes (tickangle = 45, tickfont_size = 6, showgrid=False)
fig_pib.update_yaxes( tickfont_size = 10,showgrid=False)


fig_pib.update_layout(
       
    autosize = True,
    margin = dict (l=30,r=30,t=30,b=30),
    legend = dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x= 1.02)
    )


tab_selic_ipca = go.Figure(layout ={"template": "plotly_dark"},data=[go.Table(
    header = dict (values= ['Ano', 'Mês','Selic', 'IPCA']),
    cells = dict (values = [tb_selic_ipca.Ano, tb_selic_ipca.Mês, tb_selic_ipca.Selic, tb_selic_ipca.IPCA]))
                           ])
tab_selic_ipca.update_layout(autosize = True,
                       title_text ="Selic / Ipca",
                      margin=go.Margin(l=20,r=20,t=50,b=40)
                      )

tab_cambio_export = go.Figure(layout = {"template": "plotly_dark"}, data = [go.Table(
    header = dict (values = ['Ano', 'Trimestre', 'Câmbio', 'Export']),
    cells = dict (values = [tb_cambio_export.Ano, tb_cambio_export.Trimestre, tb_cambio_export.Câmbio, 
                            tb_cambio_export.Export]))
                            ])

tab_cambio_export.update_layout (autosize= True,
                                 title_text = 'Câmbio / Exportação',
                                 margin = go.Margin (l=20,r=20,t=30,b=10)
                                 )

tab_pib = go.Figure(layout = {"template": "plotly_dark"}, data= [go.Table(
    header = dict (values = ['Ano', 'Trimestre', 'PIB', 'GPD World']),
    cells = dict (values = [tb_Pib.Ano, tb_Pib.Trimestre, tb_Pib.PIB, tb_Pib.GPD_World]))
                            ])
tab_pib.update_layout (autosize = True,
                      title_text = 'PIB',
                      margin = go.Margin(l=20,r=20,t=30,b=10)
                      )



#colocar em um eixo secundario
#fig_cambio_export.add_trace (go.Scatter (x = df_cambio_export['Ano_trimestre'], y = df_cambio_export['Export']))


fig_cambio_export.update_xaxes (tickangle = 45, tickfont_size = 6, dtick = "M1", tickformat = "%b\n%Y")        


app.layout = dbc.Container([
    dbc.Row([
        dbc.Col(
            html.H5("Conjuntura Econômica", style ={"margin-top": "10px", 'margin-botton': '40px'}), md =5        
        ),
        dbc.Col(md = 7)             
        
    ]),
    
    
   dbc.Row([
        dbc.Col(
                dcc.Graph (id = "tab_pib", figure = tab_pib, style = {"height":"45vh"}), md = 4
                            
            ),
            dbc.Col(
                dcc.Graph(id = "fig_pib", figure = fig_pib, style = {"height":"45vh"}),md =8
                
            )   
        
    ]),   
    
    dbc.Row([
        dbc.Col(
                dcc.Graph (id = "tab_cambio_export", figure = tab_cambio_export, style = {"height":"45vh"}), md = 4
                            
            ),
            dbc.Col(
                dcc.Graph(id = "cambio_export", figure = fig_cambio_export, style = {"height":"45vh"}),md =8
                
            )   
        
    ]),
    dbc.Row([
         dbc.Col(
                dcc.Graph (id = "tab_selic_ipca", figure = tab_selic_ipca, 
                           style = {"height":"45vh", "margin-botton": "25px"}),md = 4
                            
            ),
            dbc.Col(
                dcc.Graph(id = "selic_grafico", figure = fig_selic, style = {"height":"45vh", "margin-botton": "25px"}),md =8
                
            )       
        
    ])
    
           
    
], fluid = True)
                  
if __name__ == "__main__":
    app.run_server(debug = True, use_reloader=False)

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app '__main__'
 * Debug mode: on

C:\Users\marce\anaconda3\lib\site-packages\plotly\graph_objs\_deprecations.py:405: DeprecationWarning:

plotly.graph_objs.Margin is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.layout.Margin